### ISSUE TITLE
zero F1 scores for bert-large-uncased situated-AP

### ISSUE THREAD

**Issue by zhaozj89** [mbforbes/physical-commonsense#1]
Hi, I used `python -m pc.bert --task "situated-AP" --epochs 1` to run the BERT experiment with the default `bert-large-uncased` model, but got all zero F1 scores.

As a trial, I used `bert-base-uncased`, and can get slightly lower F1 scores as `micro: 0.35993784432829495, macro affordance: 0.3504160618215077, macro property: 0.2317239609747913`

Any idea? Thanks.

PS: I use two GTX 1080 Ti cards.

**Comment by mbforbes** [comment]
Hey there — wow, I'm so sorry that I never saw this issue! I just checked my inbox and GitHub never sent me an email that you opened this. Truly bizarre.

As a super belated answer, you might have guessed from my comment about using `--epochs 1` to prevent zero F1 scores, but BERT can simply overfit on this task and get zero F1 scores. Using `--epochs 1` helped, but it didn't solve the problem, so it's still possible to run into even after 1 epoch.

My solution was the simple one: try running again 😂 . Fortunately for NLP, more recent models seem to have helped somewhat with stability.

Apologies again!

**Comment by zhaozj89** [comment]
Thanks for the comment. Never mind. Great work!
